### ISSUE TITLE
simple CORS example should use a scheme+hostname

### ISSUE THREAD

**Issue by covener** [OpenLiberty/guide-cors#109]
finish/src/test/java/it/io/openliberty/guides/cors/TestData.java and the server.xml CORS config should use http://openliberty.io rather than a bare hostname.

Origin request headers and Access-Control-Allow-Origin response headers are scheme + host + optional port.

Unfortunately if you simulate a cross-origin request with a non browser and make the same mistake on both ends, the CORS Feature will echo back the hostname in the Origin header.

**Comment by gkwan-ibm** [comment]
close
- the guide was updated
