### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-cors#28]
**Enabling a simple CORS configuration**
- [x] "Now we will test the simple CORS configuration that you added. Add the `testSimpleCorsRequest` method to..." -> The `testSimpleCorsRequest` hotspot does not highlight the method, it just changes to the file. This should either be re-worded, or the hotspot should highlight the method. 
- [x] Should the `true` and `MyHeader` in the value section of the 3rd table be hotspotted? Similar values are hotspotted in the **enabling a preflight CORS configuration** section

**Enabling a preflight CORS configuration**
- [x] "Add two new attributes:" -> The bolded hotspots look really awkward. I think this might work better in a bulleted list or something similar.

**Comment by justineechen** [comment]
I don't think `true`,  `MyHeader` shouldn be hot spotted because there is a lot of text in the right side of the table in this case. 

https://github.com/OpenLiberty/guide-cors/commit/33a96eba5a9359a975fc547316452b172269d13f

**Comment by andrewdes** [comment]
**Enabling CORS**
- [ ] Throughout this section you are told to replace files, then right before running `mvn install` it says: "Go to the start/ directory and run the following command:" 

I think we should stay consistent with other guides and tell the users to navigate to the start directory at the beginning of this section. This would also eliminate the need to have `start` in all the paths throughout this section (i.e. `start/src/main/java/io/openliberty/guides/cors/`)

- [ ] "Add a simple CORS configuration to the server.xml file in the start/main/liberty/config/ directory:" This path is wrong, should be src/main/liberty/config/

- [ ] After replacing the server configuration file and the TestCors class as instructed, `mvn install` failed with the following error: 
![image](https://user-images.githubusercontent.com/22628575/52735545-e4fe1480-2f95-11e9-9e70-f8dad97213d3.png)
