### ISSUE TITLE
Not enough explanation of CORS values

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guide-cors#29]
I have forwarded another IBMer to this guide as they did not know much about how CORS works in Liberty. They came back to me stating that the guide does not really go into any detail about what all these CORS settings actually do and just tells you to set specific vaules. CORS in my opinion has very specific configuration for different environments so not having an explanation about what all these configurations do make this guide pointless and as a result I have then had to go and Google most of the information I require about CORS. 

My advice is to just give one sentence about each configuration setting rather than saying just set this and the user just presume that is what they need.

**Comment by yeekangc** [comment]
@jamiecoleman92, can you or the IBMer elaborate on "CORS in my opinion has very specific configuration for different environments so not having an explanation about what all these configurations do make this guide pointless and as a result I have then had to go and Google most of the information I require about CORS"?

I am not sure I fully follow.  Specifics regarding missing information that one believes will be helpful.

**Comment by jamiecoleman92** [comment]
Hi @yeekangc 

I was referring to specifically this section:

Expect the following response headers and values if the simple CORS request is successful, and the server is correctly configured:

Header | Value
-- | --
Access-Control-Allow-Origin | openliberty.io
Access-Control-Allow-Credentials | true
Access-Control-Expose-Headers | MyHeader

I could not see at a glance any information about what these settings do for me as a user. Maybe adding in a little description like what was done with the table above?

**Comment by yeekangc** [comment]
That was from the specification.  Not really Open Liberty-specific.  I think we can add to it.  Thank you, @jamiecoleman92.

**Comment by jamiecoleman92** [comment]
Not specific to Open Liberty but specific to CORS so in my opinion anyway I think adding a little bit of info there would be good! Thank you for getting back to me in such a short amount of time @yeekangc

**Comment by justineechen** [comment]
@jamiecoleman92 I've added more description about the header for CORS, if you think that there needs to be more detail or anything that has to be added please let me know and feel free to re-open this issue! Thank you for letting us know about this problem.
