### ISSUE TITLE
Spell out what CORS means in either the title or the first sentence (or both)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-cors#3]
(in addition to the acronym)

I had no idea what CORS stands for (even though I'd previously looked it up). "Cross-Origin Resource Sharing", on the other hand, sounds quite useful (if a little oblique still). :) It at least makes me want to find out more.

**Comment by yeekangc** [comment]
@Ahmad-Ayyoub submitted a PR:  https://github.com/OpenLiberty/guide-cors/pull/4

Should review how it shows on the website to see what is best.

ID should review too.

**Comment by yeekangc** [comment]
Please post a screen cap of how it will look like on the website, @Ahmad-Ayyoub, and we can see what is the best way to go.

**Comment by yeekangc** [comment]
![](https://files.slack.com/files-pri/T27SFGS2W-F7J1Z9ZV1/screenshot_552.png)

**Comment by Ahmad-Ayyoub** [comment]
<img width="616" alt="screenshot 552" src="https://user-images.githubusercontent.com/29547519/31561932-98e913fe-b027-11e7-916d-d590e71dc870.png">
<img width="714" alt="screenshot 553" src="https://user-images.githubusercontent.com/29547519/31561934-98f5e14c-b027-11e7-9484-51f1bbaeafeb.png">

**Comment by Ahmad-Ayyoub** [comment]
<img width="891" alt="screenshot 551" src="https://user-images.githubusercontent.com/29547519/31561951-a7aa10f0-b027-11e7-9f5b-f4c5c922c7c2.png">
<img width="616" alt="screenshot 552" src="https://user-images.githubusercontent.com/29547519/31561952-a7b3d8e2-b027-11e7-9f9d-85c89791aa06.png">

**Comment by yeekangc** [comment]
Looks like we have enough space on the card for the longer name and it looks fine.

If @lauracowen and @sishida have no issue, @sishida can review the PR, and we can merge.

**Comment by sishida** [comment]
The screenshots look good to me!

**Comment by sishida** [comment]
Oh, do we want to add CORS to the title, too? That's the only thing I can think of to change:
Enabling Cross-Origin Resource Sharing (CORS) in Open Liberty

**Comment by yeekangc** [comment]
That's not a bad idea especially since it won't take too much space.

**Comment by Ahmad-Ayyoub** [comment]
I will fix that

**Comment by Ahmad-Ayyoub** [comment]
<img width="487" alt="screenshot 554" src="https://user-images.githubusercontent.com/29547519/31562553-e4d9aa92-b029-11e7-8027-2f20ffb93b93.png">
<img width="990" alt="screenshot 555" src="https://user-images.githubusercontent.com/29547519/31562554-e4e9936c-b029-11e7-9892-f389210cb509.png">

**Comment by sishida** [comment]
Review added and approved!

**Comment by Ahmad-Ayyoub** [comment]
Thanks!
