### ISSUE TITLE
Accessibility Verification Testing (AVT)

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-cors#59]
- [x] AVT 1 = Automated testing
  - use accessibility checker
  - https://github.com/OpenLiberty/guides-common/issues/486
- [x] AVT 2 = Manual testing
  - a picture requires alternative text to describe the image
  - table requires alternative text
  - test color contrast
  - test using keyboard instead of mouse
- [x] AVT 3 = Screen Reader testing
  - use JAWS screen reader

**Comment by jj-zhang** [comment]
### AVT 1: Automated testing

![image](https://user-images.githubusercontent.com/24790572/87000087-38bc5f80-c182-11ea-81bb-d7ec71a1a6c9.png)

**Comment by jj-zhang** [comment]
Tested JAWS using screen reader and work properly
