### ISSUE TITLE
Links to docs for further config options

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-cors#69]
Consider linking from the guide to the config options doc: https://www.openliberty.io/docs/latest/reference/config/cors.html Eg in this guide there's a small table showing what config options have been used and what they mean. But there are other config options too that might be of interest (but shouldn't be included in the guide) so you could link to the docs for them.

This issue could be applied to all guides where there are other config options - just find the relevant config options in the OL docs.

**Comment by gkwan-ibm** [comment]
close
- added the doc link
