### ISSUE TITLE
Remove TM and R symbols in the guides.

### ISSUE THREAD

**Issue by sishida** [OpenLiberty/guide-cors#7]
The first sentence in this guide contains a "TM" next to "Java." We have decided to avoid using trademark symbols, so this symbol should be removed along with any others that might be present.

**Comment by sishida** [comment]
@yeekangc and @Ahmad-Ayyoub: I removed the (TM) and committed the change directly to the master branch. Do you need to review/close?

I think this is only my second time working a defect for Open Liberty/first time opening my own, so if there's anything else I need to do to resolve it, please let me know! :) Thank you!

**Comment by yeekangc** [comment]
It will be good if it was done as a PR.  But, no problem.  Saw your change and it works.  Thank you, @sishida.

https://github.com/OpenLiberty/guide-cors/commit/77f8dab69c43236e5c8f266fab2d90128e3a5a11
