### ISSUE TITLE
Incorrect statement

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-cors#82]
the following line is incorrect:
> When clients, such as browsers, send simple CORS requests to servers on different domains, the clients include an Origin header with the client host name as the value.

The Origin header's value should not be the client (browser) host name - it should be the original (referring) host name.
So, for example, suppose I'm the client (on host: mymacbook), and I'm accessing weather.com which has a web page with some javascript in it to get the current time from time.gov.  The Origin header on the request to time.gov would be weather.com , not mymacbook.

**Comment by jakub-pomykala** [comment]
PR open [here](https://github.com/OpenLiberty/guide-cors/pull/98)

**Comment by jakub-pomykala** [comment]
[PR to prod](https://github.com/OpenLiberty/guide-cors/pull/100)

**Comment by gkwan-ibm** [comment]
close
- the issue was fixed
